[mgr]
prepend_keymap = [
	{ on = "i", run = "arrow prev", desc = "Previous file" },
	{ on = "k", run = "arrow next", desc = "Next file" },
	{ on = "j", run = "leave"},
	{ on = "<Enter>", run = "enter", desc = "Enter directory" },
]
