name: Vault Publish

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  DOCKER_REGISTRY: "ghcr.io"
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
  PROJECT_FILE: ./src/Vault.Web/Vault.Web.csproj
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_FILE }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_FILE }} --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ${{ env.PROJECT_FILE }} -c Release --no-build --output ./app
  
      - name: Convert Image Name to Lowercase
        run: echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./build/Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          